### ISSUE TITLE
HW2ISSUE#10 Incorrect styles using

### ISSUE THREAD

**Issue by DennyTim** [Rahul-k25/Simple-Page-HW2#10]
https://github.com/Rahul-k25/Simple-Page/blob/f1f8168b31231abbd2c9ab9dd7a1cd22710c401c/HW2/index.html#L25

Your nav menu can be rewritten in the next way:
![image](https://user-images.githubusercontent.com/44003977/215343054-f8391466-decd-43e3-9ce1-6690fe32bb2e.png)

```html

<div class="left-menu">
                <a href="#" class="left-menu__subPart">Ramda</a>
                <a href="#" class="left-menu__subPart">Why Ramda?</a>
                <a href="#" class="left-menu__subPart">What's Different?</a>
                <a href="#" class="left-menu__subPart">Introduction</a>
                <a href="#" class="left-menu__subPart">Philosophy</a>
</div>
```

```css
.left-menu {
    width: 344px;
    margin-top: 51px;
    border: 1px solid black;
    list-style: none;
    align-self: start;
}

.left-menu__subPart:hover {
    padding-left: 70px;
    transition: All 0.4s ease;
    color: black;
    background: rgb(220, 220, 220);
}

.left-menu__subPart {
    display: block;
    padding-left: 44px;
    font-size: 27px;
    padding-top: 20px;
    padding-bottom: 20px;
    text-decoration: none;
    color: rgb(70, 87, 99);
}
```

Just one more moment, those selectors can be also named correctly in the following way: `left-sidebar`, `left-sidebar__item`,`left-sidebar__hover`.
